Script started on Thu 26 Oct 2017 05:07:56 PM PDT
]0;hyfong@zuma:~/hw2[hyfong@zuma ~/hw2]$ exit./PhotoLab[22G[40@gcc PhotoLab.c -Wall -g -ansi -std=c99 -o [72G[22Gvi PhotoLab.c[K[22Ggcc PhotoLab.c -Wall -g -ansi -std=c99 -o PhotoLab
]0;hyfong@zuma:~/hw2[hyfong@zuma ~/hw2]$ ./PhotoLab
HSSOE.ppm was read.
-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice:11
HSSOE.ppm was read.
Black and White operation is done!

bw.ppm was saved. 
bw.jpg was stored.
Black and White tested!

HSSOE.ppm was read.
Negative operation is done

negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

HSSOE.ppm was read.
Color filter operation is done! 

colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

HSSOE.ppm was read.
VFlip operation is done!

vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

HSSOE.ppm was read.
VMirror operation is done!vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

HSSOE.ppm was read.
Edge operation is done!

edge.ppm was saved. 
edge.jpg was stored.
Edge tested!

HSSOE.ppm was read.
Shuffle operation is done!shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice:12
]0;hyfong@zuma:~/hw2[hyfong@zuma ~/hw2]$ exit
exit

Script done on Thu 26 Oct 2017 05:08:11 PM PDT
