Script started on Wed 08 Nov 2017 05:32:16 PM PST
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ make clean
rm -f PhotoLab.o
rm -f Advanced.o
rm -f DIPs.o
rm -f FileIO.o
rm -f PhotoLab
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ make
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o 
gcc -Wall -ansi -std=c99 -c FileIO.c -o FileIO.o
gcc -Wall -ansi -std=c99 -c PhotoLab.c -o PhotoLab.o
gcc -Wall -ansi -std=c99 -c DIPs.c -o DIPs.o
gcc -Wall -ansi -std=c99 -o PhotoLab Advanced.o FileIO.o PhotoLab.o DIPs.o
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ ./PhotoLab
HSSOE.ppm was read.
-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Add noise to an image
12: Sharpen an image
13:Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
please make your choice:15
HSSOE.ppm was read.
Black and White operation is done!

bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
Negative operation is done

negative.ppm was saved. 
negative.jpg was stored.
HSSOE.ppm was read.
Color filter operation is done! 

colorfilter.ppm was saved. 
colorfilter.jpg was stored.
HSSOE.ppm was read.
VFlip operation is done!

vflip.ppm was saved. 
vflip.jpg was stored.
HSSOE.ppm was read.
VMirror operation is done!vmirror.ppm was saved. 
vmirror.jpg was stored.
HSSOE.ppm was read.
Edge operation is done!

edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
Shuffle operation is done!bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Add noise to an image
12: Sharpen an image
13:Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
please make your choice:16
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ make PhotoLabTest
gcc -Wall -ansi -std=c99 -g -ddebug -c Advanced.c -o Advanced.o
cc1: warning: unrecognized gcc debugging option: d
cc1: warning: unrecognized gcc debugging option: e
cc1: warning: unrecognized gcc debugging option: b
cc1: warning: unrecognized gcc debugging option: u
cc1: warning: unrecognized gcc debugging option: g
gcc -Wall -ansi -std=c99 -g -ddebug -c PhotoLab.c -o PhotoLab.o
cc1: warning: unrecognized gcc debugging option: d
cc1: warning: unrecognized gcc debugging option: e
cc1: warning: unrecognized gcc debugging option: b
cc1: warning: unrecognized gcc debugging option: u
cc1: warning: unrecognized gcc debugging option: g
gcc -Wall -ansi -std=c99 -g -ddebug -c FileIO.c -o FileIO.o
cc1: warning: unrecognized gcc debugging option: d
cc1: warning: unrecognized gcc debugging option: e
cc1: warning: unrecognized gcc debugging option: b
cc1: warning: unrecognized gcc debugging option: u
cc1: warning: unrecognized gcc debugging option: g
gcc -Wall -ansi -std=c99 -g -ddebug -c DIPs.c -o DIPs.o
cc1: warning: unrecognized gcc debugging option: d
cc1: warning: unrecognized gcc debugging option: e
cc1: warning: unrecognized gcc debugging option: b
cc1: warning: unrecognized gcc debugging option: u
cc1: warning: unrecognized gcc debugging option: g
gcc -Wall -g -ddebug Advanced.o FileIO.o DIPs.o PhotoLab.o
./PhotoLabTest
HSSOE.ppm was read.
-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Add noise to an image
12: Sharpen an image
13:Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
please make your choice:15
HSSOE.ppm was read.
Black and White operation is done!

bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
Negative operation is done

negative.ppm was saved. 
negative.jpg was stored.
HSSOE.ppm was read.
Color filter operation is done! 

colorfilter.ppm was saved. 
colorfilter.jpg was stored.
HSSOE.ppm was read.
VFlip operation is done!

vflip.ppm was saved. 
vflip.jpg was stored.
HSSOE.ppm was read.
VMirror operation is done!vmirror.ppm was saved. 
vmirror.jpg was stored.
HSSOE.ppm was read.
Edge operation is done!

edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
Shuffle operation is done!bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
-----------------------------------------
1: Load a PPM Image
2: Save an image in PPM and JPEG Format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter animage
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror and image vertically
10: Add Border to an image
11: Add noise to an image
12: Sharpen an image
13:Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
please make your choice:16
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ touch Advanced.c
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ make PhotoLab
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o 
gcc -Wall -ansi -std=c99 -o PhotoLab Advanced.o FileIO.o PhotoLab.o DIPs.o
]0;hyfong@zuma:~/hw3[hyfong@zuma ~/hw3]$ exit
exit

Script done on Wed 08 Nov 2017 05:32:51 PM PST
